"""GraphRAG Relationship Extraction Agent.

Uses LLM to infer AFFECTS and CORRELATES_WITH relationships.
Deterministic relationships (CONNECTS_TO, LOCATED_IN, etc.) are
already generated by rules in Stage 2.

Follows §D.2 rules from UrbanGraph-SG-report.md:
- Only infers AFFECTS and CORRELATES_WITH
- Every inferred relationship must have an `evidence` field
- No entities can be created during relationship extraction
- Source and target must exist in the entity table
"""

import json
import logging
from pathlib import Path
from typing import Any

import pandas as pd

from src.config import config
from src.graphrag.llm_client import LLMClient, load_prompt, load_few_shot_examples

logger = logging.getLogger(__name__)


class RelationshipExtractionAgent:
    """Extract inferred relationships using LLM."""

    def __init__(self, llm: LLMClient | None = None):
        self.llm = llm or LLMClient()
        self.prompt = load_prompt("relationship_extraction")
        self.few_shots = load_few_shot_examples("relationship_extraction")

    def extract_all(
        self,
        entities_path: Path | None = None,
        community_texts_dir: Path | None = None,
        output_path: Path | None = None,
        dry_run: bool = False,
    ) -> pd.DataFrame:
        """Extract LLM-inferred relationships.

        Args:
            entities_path: Path to GraphRAG entities.parquet
            community_texts_dir: Community text files
            output_path: Output path for relationships
            dry_run: Only process 1 file

        Returns:
            DataFrame with inferred relationships
        """
        if entities_path is None:
            entities_path = config.data_dir / "graphrag" / "input" / "entities.parquet"
        if community_texts_dir is None:
            community_texts_dir = config.data_dir / "processed" / "community_texts"
        if output_path is None:
            output_path = config.data_dir / "graphrag" / "output" / "inferred_relationships.parquet"
        output_path.parent.mkdir(parents=True, exist_ok=True)

        # Load existing entities for validation
        if not entities_path.exists():
            logger.error("Entities file not found: %s", entities_path)
            return pd.DataFrame()

        entities_df = pd.read_parquet(entities_path)
        entity_ids = set(entities_df["id"].tolist())

        # Build a compact entity reference for the prompt
        entity_refs = _build_entity_reference(entities_df)

        all_relationships: list[dict[str, Any]] = []

        txt_files = sorted(community_texts_dir.glob("*.txt"))
        if dry_run:
            txt_files = txt_files[:2]

        for i, txt_file in enumerate(txt_files):
            text = txt_file.read_text(encoding="utf-8")
            if len(text.strip()) < 100:
                continue

            area_name = txt_file.stem.replace("_", " ").title()

            try:
                rels = self._extract_from_text(text, entity_refs, area_name)
                # Validate: all source/target must be in entity_ids
                for rel in rels:
                    if rel.get("source_id") in entity_ids and rel.get("target_id") in entity_ids:
                        all_relationships.append(rel)
            except Exception as e:
                logger.warning("Failed relationships for %s: %s", area_name, e)
                continue

            if (i + 1) % 10 == 0:
                logger.info(
                    "Relationship extraction: %d/%d, %d inferred so far",
                    i + 1, len(txt_files), len(all_relationships),
                )

        df = pd.DataFrame(all_relationships)
        if not df.empty:
            # Ensure required columns
            for col in ["source", "target", "relation", "description", "weight", "generation"]:
                if col not in df.columns:
                    if col == "source" and "source_id" in df.columns:
                        df["source"] = df["source_id"]
                    elif col == "target" and "target_id" in df.columns:
                        df["target"] = df["target_id"]
                    elif col == "generation":
                        df[col] = "llm_inference"
                    elif col == "weight":
                        df[col] = 0.7
                    elif col == "description":
                        df[col] = ""

            df.to_parquet(output_path, index=False)
            logger.info(
                "Relationship extraction complete: %d inferred → %s",
                len(df), output_path,
            )

        return df

    def _extract_from_text(
        self, text: str, entity_refs: str, area_name: str,
    ) -> list[dict[str, Any]]:
        """Extract relationships from a single community text."""
        user_prompt = self.prompt.get("user", "{text}")
        if "{entities}" in user_prompt:
            user_prompt = user_prompt.replace("{entities}", entity_refs[:2000])
        if "{text}" in user_prompt:
            user_prompt = user_prompt.replace("{text}", text[:3000])

        system_prompt = f"""{self.prompt['system']}

Context: {area_name} planning area, Singapore.

Available entities:
{entity_refs[:3000]}

ONLY create AFFECTS and CORRELATES_WITH relationships using the entity IDs above.
"""
        try:
            response = self.llm.chat_with_json_output(
                system_prompt=system_prompt,
                user_prompt=user_prompt,
                label=f"rel_extract_{area_name}",
                max_tokens=2000,
            )

            if "parse_error" in response:
                return []

            if isinstance(response, list):
                return response
            if isinstance(response, dict) and "relationships" in response:
                return response["relationships"]

            return []

        except RuntimeError as e:
            logger.error("LLM relationship extraction failed for %s: %s", area_name, e)
            return []


def _build_entity_reference(df: pd.DataFrame) -> str:
    """Build a compact entity reference string for prompt context."""
    lines = []
    # Group by type
    for etype in df["type"].unique():
        subset = df[df["type"] == etype]
        lines.append(f"\n## {etype.upper()} ({len(subset)} entities)")
        for _, row in subset.head(30).iterrows():  # limit per type
            name = row.get("name", row.get("id", ""))
            desc = row.get("description", "")
            lines.append(f"- {row['id']}: {name}. {desc}")
    return "\n".join(lines)


if __name__ == "__main__":
    logging.basicConfig(
        level=getattr(logging, config.settings.log_level),
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    )
    agent = RelationshipExtractionAgent()
    df = agent.extract_all(dry_run=True)
    if not df.empty:
        print(f"Inferred {len(df)} relationships")
        print(df.head())
    stats = agent.llm.get_stats()
    print(f"\nLLM Stats: {json.dumps(stats, indent=2)}")
